name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update Gem
        run: gem update --system
      - name: Install Gems
        run: bundle install

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test
